export const CREDENTIALS = process.env.CREDENTIALS === 'true';
export const {
  NODE_ENV,
  PORT,
  DB_HOST,
  CLIENT_ID,
  CLIENT_SECRET,
  SIGNING_SECRET,
  GRAPHQL_URL,
  LOG_FORMAT = 'info',
  LOG_DIR = '../logs',
  ORIGIN,
  MAILCHIMP_CLIENT_ID,
  MAILCHIMP_CLIENT_SECRET,
  SERVER_URL,
  LOGGER_PRETTY_PRINT,
} = process.env;
