export enum WEBHOOK_ACTION {
  TEST = 'TEST',
  UPDATE_SETTINGS = 'UPDATE_SETTINGS',
  GET_SETTINGS = 'GET_SETTINGS',
  SUBSCRIPTION = 'SUBSCRIPTION',
  LOAD_BLOCK = 'LOAD_BLOCK',
  CALLBACK_BLOCK = 'CALLBACK_BLOCK',
  Callback = 'Callback',
  APP_UNINSTALLED = 'APP_UNINSTALLED',
  INTERACTION = 'INTERACTION',
}
